config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: "home"

  get 'about' => 'pages#about', as: 'about'
  resources :posts do
  resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name:"admin", password: "1313", exepct: [:index, :show]
  def create
    @post = Post.find(params[:post_id])
    @comments = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'News'
    @text = "NEWS UPDATE COMING SOON"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all

  end

  def new
    @post = Post.new

  end

  def show
    @post = Post.find(params[:id])
  end
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
    def destroy
      @post = Post.find(params[:id])

      @post.destroy
      redirect_to posts_path
    end
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)

    if(@post.save)
    redirect_to @post
    else
      render 'new'
    end

  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogМilan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <html>
  <head>
    <meta charset="utf-8">
    <title>Фон</title>
    <style>
      body {
        background: url(https://www.logo.wine/a/logo/A.C._Milan/A.C._Milan-Logo.wine.svg)no-repeat;
        moz-background-size: 100%;
        webkit-background-size: 100%;
        background-size: 100%;
        <body style="background-attachment:fixed" topmargin="0"
      }
    </style>
  </head>
  <body>
  <p></p>
  </body>
  </html>

  <body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-black red-bottom black-sm">
    <h5 class="my-0 mr-md-auto font-weight-absolute">AC.Milan</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <span class="btn btn-success" ><%= link_to "Home" ,home_path %></span>
    <span class="btn btn-light"><%= link_to "News" ,about_path %></span>
    <span class="btn btn-danger"><%= link_to 'Add post', new_post_path %></span>
  </div>
  <div class='container'>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Фон</title>
  <style>
    body {
      background: url(https://www.logo.wine/a/logo/A.C._Milan/A.C._Milan-Logo.wine.svg)no-repeat;
      moz-background-size: 100%;
      webkit-background-size: 100%;
      background-size: 100%;
      <body style="background-attachment:fixed" topmargin="0"
    }
  </style>
</head>
<body>
<p>...</p>
</body>
</html>
<h2><%= @heading %></h2>
<p><%= @text %></p>

app/views/posts/edit.html.erb
<h4>edit</h4>
<%= form_for :post, url: post_path(@post),method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Name<br>
    <%= f.text_field(:title,{:class => 'form-control' }) %>
  </p>
  <p>
    Text Posts<br>
    <%= f.text_area(:body,{:class => 'form-control' }) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-danger'})%>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>All posts Milan</h1>
<% @post.each do |post| %>
  <div class="alert alert-light"></div>
  <h3> <%= post.title %></h3>
  <p> <%= post.body %></p>
  <%= link_to "more", post_path(post), :class => 'btn btn-outline-dark' %>
<% end %>

app/views/posts/new.html.erb
<html>
<head>
  <meta charset="utf-8">
  <title>Фон</title>
  <style>
    body {
      background: #F7F7F7 url(https://www.logo.wine/a/logo/A.C._Milan/A.C._Milan-Logo.wine.svg) no-repeat;
      -moz-background-size: 100%;
      -webkit-background-size: 100%;
      -o-background-size: 100%;
      background-size: 100%;
      color: #2E2F30;
    }
  </style>
</head>
<body>
<p></p>
</body>
</html
<h4>New Posts</h4>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
<p>
   Name<br>
  <%= f.text_field(:title,{:class => 'form-control' }) %>
</p>
  <p>
    Text Posts<br>
    <%= f.text_area(:body,{:class => 'form-control' }) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-danger'})%>
  </p>
<%end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h1><%= @post.body %></h1>
<hr>
<%= link_to "edit", edit_post_path(@post), :class=> 'btn btn-dark' %>
<%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "want to delete?"},:class=> 'btn btn-danger' %>
<hr>
<h2>All Comments</h2>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.usernam %></strong>:<%= comment.body %></p>
  </div>

<% end %>



<hr>
<h2>Comments</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    User Name<br>
    <%=f.text_field(:usernam, {:class => 'form-control'}) %>
  </p>
  <p>
    Comments<br>
    <%=f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%=f.submit("Add", {:class => 'btn btn-warning'}) %>
  </p>
<%end %>